---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueprint-service
  namespace: default
  labels:
    app: blueprint-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueprint-service
  template:
    metadata:
      labels:
        app: blueprint-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "blueprint-service"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
    spec:
      containers:
      - name: blueprint-service
        image: siccardev.azurecr.io/blueprint-service:latest
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: "#{SERILOG__MINIMUMLEVEL}#"
        - name: TENANTISSUER
          value: "#{TENANTISSUER}#"
        - name: APP__API__TOKEN
          value: "#{APP__API__TOKEN}#"
        - name: DaprSecret
          value: "#{DaprSecret}#"
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"          
        ports:
        - containerPort: 80
        imagePullPolicy: Always