---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  selector:
    app: tenant-service
  ports:
  - port: 8080
    targetPort: 8080
    name: "http"
  - port: 8443
    targetPort: 8443
    name: "https"