apiVersion: v1
kind: PersistentVolume
metadata:
  name: keys-azurefile
spec:
  storageClassName: keys-azurefile
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/app/data"
  persistentVolumeReclaimPolicy: Retain