apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blueprintstore
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "[n]siccardev.mongo.cosmos.azure.com:10255"
  - name: username
    secretKeyRef:
      name: statestore
      key: username
  - name: password
    secretKeyRef:
      name: statestore
      key: token
  - name: params
    value: "?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@[n]siccardev@"
  - name: database
    value: blueprintstore
  - name: collectionName
    value: DAPR
scopes:
- blueprint-service