---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tenantstore
  labels:
    app: tenant-service
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: "#{COSMOS_URL}#"   
  - name: masterKey
    value: "#{COSMOS_KEY}#"
  - name: database
    value: "#{COSMOS_DATABASE}#"
  - name: collection
    value: tenantstore
scopes:
- tenant-service