---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueprint-service
  namespace: default
  labels:
    app: blueprint-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueprint-service
  template:
    metadata:
      labels:
        app: blueprint-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "blueprint-service"
        dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
        dapr.io/http-max-request-size: "16"
    spec:
      containers:
      - name: blueprint-service
        image: {{ACR}}/blueprint-service:latest
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{SERILOG__MINIMUMLEVEL}}
        - name: TENANTISSUER
          value: {{TENANTISSUER}}
        - name: APP__API__TOKEN
          valueFrom:
            secretKeyRef:
              name: app-api-token
              key: token
        - name: DaprSecret
          valueFrom:
            secretKeyRef:
              name: daprsecret
              key: secret
        resources:
          requests:
            memory: "96Mi"
            cpu: "100m" 
          limits:
            memory: "128Mi"
            cpu: "250m"          
        ports:
        - containerPort: 80
        imagePullPolicy: Always