---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-service
  namespace: default
  labels:
    app: validator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-service
  template:
    metadata:
      labels:
        app: validator-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "validator-service"
        dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
        dapr.io/app-token-secret: "app-api-token"
    spec:
      containers:
      - name: validator-service
        image: {{ACR}}/validator-service:latest
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{SERILOG__MINIMUMLEVEL}}
        - name: APP__API__TOKEN
          valueFrom:
            secretKeyRef:
              name: app-api-token
              key: token
        - name: DaprSecret
          valueFrom:
            secretKeyRef:
              name: daprsecret
              key: secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"          
        ports:
        - containerPort: 80
        imagePullPolicy: Always
