---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service
  namespace: default
  labels:
    app: tenant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-service
  template:
    metadata:
      labels:
        app: tenant-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "tenant-service"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
    spec:
      containers:
      - name: tenant-service
        image: {{ACR}}/tenant-service:latest
        imagePullPolicy: Always
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{SERILOG__MINIMUMLEVEL}}
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "5iccar"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "default.pfx"
        - name: TENANTREPOSITORY__MONGODBSERVER
          value: {{TENANTREPOSITORY__MONGODBSERVER}}
        - name: TENANTREPOSITORY__DATABASENAME
          value: {{TENANTREPOSITORY__DATABASENAME}}
        - name: TENANTISSUER
          value: {{TENANTISSUER}}
        - name: DEFAULTTENANT
          value: {{DefaultTenant}}
        - name: APP__API__TOKEN
          valueFrom:
            secretKeyRef:
              name: daprauth
              key: token
        - name: DaprSecret
          valueFrom:
            secretKeyRef:
              name: daprauth
              key: secret
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"  
        volumeMounts:
          - name: keydata
            mountPath: "/app/data"
        ports:
        - containerPort: 80
        - containerPort: 443
      volumes:
        - name: keydata
          persistentVolumeClaim:
            claimName: keys-azurefile  
    